### ISSUE TITLE
CPU-only Dockerfile

### ISSUE THREAD

**Issue by hannesrichter** [koi-learning/koi-core#28]
For deploying the core in a non gpu-accelerated environment, we need a nee Dockerfile. While changing this, we should consider switching to a prebuild tensorflow Image. Maybe even supply a framework-free Dockerfile?

**Comment by jonau** [comment]
Is the Dockerfile fundamentally different in an non accelerated environment? As far as I know the installations files for tensorflow don't differ anymore between those. Maybe a simple switch will do?

I would say a framework-free dockerfiles is a good addition. There is also the reasoning because we are framework independent to have other framework ready docker files available. But I see that we currently cant test these. So yes I think a Base Image with additional one or two tensorflow images makes perfectly sense

**Comment by hannesrichter** [comment]
dockerfile was reworked and we now publish prebuild docker images for the koi-projects
